# Generated by Django 4.0.5 on 2022-07-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prova', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='color',
            field=models.CharField(blank=True, default='FFFFFF', max_length=6),
        ),
    ]
